enableScripts: false

nodeLinker: node-modules

# TODO - Bump this to 7 days once semantic-release 25.0.1 has been out that long
npmMinimalAgeGate: 2880

npmPreapprovedPackages:
  - "@electron/*"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
