name: Semantic Trusted Release Action
description: Publish a semantic release npm package via trusted publishing

inputs:
  github-token:
    description: GitHub app installation token to use with semantic-release
    required: true

outputs:
  new-release-published:
    description: Whether a new release was published
    value: ${{ steps.semantic-release.outputs.new-release-published }}
  new-release-version:
    description: The version of the new release, if one was published
    value: ${{ steps.semantic-release.outputs.new-release-version }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 24.10.0

    - name: Set up publishing environment
      env:
        DIR: /tmp/semantic-release-packages
      run: |
        mkdir $DIR
        cp ${{ github.action_path }}/package.json $DIR/package.json
        cp -r ${{ github.action_path }}/.yarn $DIR/.yarn
        cp ${{ github.action_path }}/.yarnrc.yml $DIR/.yarnrc.yml
        cp ${{ github.action_path }}/yarn.lock $DIR/yarn.lock
        cd $DIR
        yarn install --immutable
        echo "$DIR/node_modules/.bin" >> "$GITHUB_PATH"
      shell: bash

    - name: Run semantic release
      id: semantic-release
      run: node ${{ github.action_path }}/run-semantic-release.js
      shell: bash
      env:
        DIR: /tmp/semantic-release-packages
        GITHUB_ACTION: 1
        GITHUB_TOKEN: ${{ inputs.github-token }}
